services:
  postgres:
    container_name: ecommerce-postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Ecommerce
    ports:
      - "5432:5432"
    restart: always
    networks:
      - ecommerce-network
  
  pgadmin:
    container_name: ecommerce-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - ecommerce-network
    restart: always
    depends_on:
      - postgres

  core.api:
    image: core.api
    build:
      context: .
      dockerfile: Services/Core/src/Core.API/Dockerfile
    ports:
      - "8000:80"
    networks:
      - ecommerce-network
    depends_on:
      - postgres
        
  digital-bank.api:
    image: digital-bank.api
    build:
      context: .
      dockerfile: Services/DigitalBank/src/DigitalBank.API/Dockerfile
    ports:
      - "9000:80"
    networks:
      - ecommerce-network
    depends_on:
      - postgres
  
  test-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

networks:
  ecommerce-network:
    driver: bridge
